### ISSUE TITLE
Programmatically add Gazebo Buoyancy Plugin

### ISSUE THREAD

**Issue by miloknowles** [boschresearch/pcg_gazebo_pkgs#53]
Hi,

I'm trying to add the [Gazebo Buoyancy plugin](http://gazebosim.org/tutorials?tut=hydrodynamics&cat=physics) to my model. Basically, I would like the plugin to have this exact xml:
```xml
<plugin name="BuoyancyPlugin" filename="libBuoyancyPlugin.so">
  <fluid_density>2000</fluid_density>
  <link name="body">
    <center_of_volume>1 2 3</center_of_volume>
    <volume>50</volume>
  </link>
</plugin>
```

I am able to add the `fluid_density` argument by setting the `plugin.value`:
```python
plugin = create_sdf_element("plugin")
plugin.name = "BuoyancyPlugin"
plugin.value = dict(fluid_density=999)
plugin.filename = "libBuoyancyPlugin.so"
model.add_plugin("BuoyancyPlugin", plugin)
```

Which generates this xml:
```xml
<plugin filename="libBuoyancyPlugin.so" name="BuoyancyPlugin">
  <fluid_density>999</fluid_density>
</plugin>
```

However, I'm unsure how to add this snippet of inner xml from the buoyancy plugin tutorial:
```xml
<link name="body">
  <center_of_volume>1 2 3</center_of_volume>
  <volume>50</volume>
</link>
```

Any help you can give would be appreciated!

Thank you,
Milo

**Comment by musamarcusso** [comment]
Hi, I transferred this project mostly to this Python project https://github.com/boschresearch/pcg_gazebo. You can also install it as sudo pip3 install pcg-gazebo. Please let me know if the errors persist with that installation.
