### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by Georacer** [boschresearch/pcg_gazebo_pkgs#54]
Hello there!

I'm surprised this is the only package I could find for a Python API for SDF generation.
Good job, I guess!

Do you have any plans for ROS2 support?

All the best!

**Comment by musamarcusso** [comment]
Hi, I transferred this project mostly to this Python project https://github.com/boschresearch/pcg_gazebo. You can also install it as sudo pip3 install pcg-gazebo. Please let me know if the errors persist with that installation.

**Comment by Georacer** [comment]
Great! I'm currently interested in the parser (generate SDF). I'll try it soon and let you know how it went.

**Comment by Georacer** [comment]
I tried to install directly from pip3. Didn't use rosdep, because I didn't want to download the source.
While installing in a virtualenvwrapper environment on Ubuntu 20.04 I got errors building ``rtree`` and ``python-fcl``.

``rtree`` had a dependency on Ubuntu package ``libspatialindex-dev`` while
``python-fcl`` required ``liboctopmap-dev`` and ``libfcl-dev``.

After that, pip3 resolved the package fine. I managed to import it, haven't used it yet. 
Will report further.

**Comment by Georacer** [comment]
I saw that most of these dependencies were mentioned in the Readme of https://github.com/boschresearch/pcg_gazebo. I managed to create an SDF object with some simple characteristics in Python3, so deem this try successful so far. Thank you for this package!
